function LEWYSUBROGp = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  LEWYSUBROGP11 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  LEWYSUBROGP11 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  LEWYSUBROGp11 = importfile("C:\Users\OEM\Documents\AMP_1\Lab2\bez_adaptacji_data\LEWY_SUB_ROG_p1-1.txt", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Oct-2023 00:02:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["FreqHz", "SPLdB", "Phasedegrees"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LEWYSUBROGp = readtable(filename, opts);

end